import { ReactNode } from 'react';

export interface Movie {
    label: string;
    year: number;
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top (repeated twice to test performance)
export const movies: Movie[] = [
    { label: 'The Shawshank Redemption', year: 1994 },
    { label: 'The Godfather', year: 1972 },
    { label: 'The Godfather: Part II', year: 1974 },
    { label: 'The Dark Knight', year: 2008 },
    { label: '12 Angry Men', year: 1957 },
    { label: "Schindler's List", year: 1993 },
    { label: 'Pulp Fiction', year: 1994 },
    {
        label: 'The Lord of the Rings: The Return of the King',
        year: 2003,
    },
    { label: 'The Good, the Bad and the Ugly', year: 1966 },
    { label: 'Fight Club', year: 1999 },
    {
        label: 'The Lord of the Rings: The Fellowship of the Ring',
        year: 2001,
    },
    {
        label: 'Star Wars: Episode V - The Empire Strikes Back',
        year: 1980,
    },
    { label: 'Forrest Gump', year: 1994 },
    { label: 'Inception', year: 2010 },
    {
        label: 'The Lord of the Rings: The Two Towers',
        year: 2002,
    },
    { label: "One Flew Over the Cuckoo's Nest", year: 1975 },
    { label: 'Goodfellas', year: 1990 },
    { label: 'The Matrix', year: 1999 },
    { label: 'Seven Samurai', year: 1954 },
    {
        label: 'Star Wars: Episode IV - A New Hope',
        year: 1977,
    },
    { label: 'City of God', year: 2002 },
    { label: 'Se7en', year: 1995 },
    { label: 'The Silence of the Lambs', year: 1991 },
    { label: "It's a Wonderful Life", year: 1946 },
    { label: 'Life Is Beautiful', year: 1997 },
    { label: 'The Usual Suspects', year: 1995 },
    { label: 'Léon: The Professional', year: 1994 },
    { label: 'Spirited Away', year: 2001 },
    { label: 'Saving Private Ryan', year: 1998 },
    { label: 'Once Upon a Time in the West', year: 1968 },
    { label: 'American History X', year: 1998 },
    { label: 'Interstellar', year: 2014 },
    { label: 'Casablanca', year: 1942 },
    { label: 'City Lights', year: 1931 },
    { label: 'Psycho', year: 1960 },
    { label: 'The Green Mile', year: 1999 },
    { label: 'The Intouchables', year: 2011 },
    { label: 'Modern Times', year: 1936 },
    { label: 'Raiders of the Lost Ark', year: 1981 },
    { label: 'Rear Window', year: 1954 },
    { label: 'The Pianist', year: 2002 },
    { label: 'The Departed', year: 2006 },
    { label: 'Terminator 2: Judgment Day', year: 1991 },
    { label: 'Back to the Future', year: 1985 },
    { label: 'Whiplash', year: 2014 },
    { label: 'Gladiator', year: 2000 },
    { label: 'Memento', year: 2000 },
    { label: 'The Prestige', year: 2006 },
    { label: 'The Lion King', year: 1994 },
    { label: 'Apocalypse Now', year: 1979 },
    { label: 'Alien', year: 1979 },
    { label: 'Sunset Boulevard', year: 1950 },
    {
        label: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
        year: 1964,
    },
    { label: 'The Great Dictator', year: 1940 },
    { label: 'Cinema Paradiso', year: 1988 },
    { label: 'The Lives of Others', year: 2006 },
    { label: 'Grave of the Fireflies', year: 1988 },
    { label: 'Paths of Glory', year: 1957 },
    { label: 'Django Unchained', year: 2012 },
    { label: 'The Shining', year: 1980 },
    { label: 'WALL·E', year: 2008 },
    { label: 'American Beauty', year: 1999 },
    { label: 'The Dark Knight Rises', year: 2012 },
    { label: 'Princess Mononoke', year: 1997 },
    { label: 'Aliens', year: 1986 },
    { label: 'Oldboy', year: 2003 },
    { label: 'Once Upon a Time in America', year: 1984 },
    { label: 'Witness for the Prosecution', year: 1957 },
    { label: 'Das Boot', year: 1981 },
    { label: 'Citizen Kane', year: 1941 },
    { label: 'North by Northwest', year: 1959 },
    { label: 'Vertigo', year: 1958 },
    {
        label: 'Star Wars: Episode VI - Return of the Jedi',
        year: 1983,
    },
    { label: 'Reservoir Dogs', year: 1992 },
    { label: 'Braveheart', year: 1995 },
    { label: 'M', year: 1931 },
    { label: 'Requiem for a Dream', year: 2000 },
    { label: 'Amélie', year: 2001 },
    { label: 'A Clockwork Orange', year: 1971 },
    { label: 'Like Stars on Earth', year: 2007 },
    { label: 'Taxi Driver', year: 1976 },
    { label: 'Lawrence of Arabia', year: 1962 },
    { label: 'Double Indemnity', year: 1944 },
    {
        label: 'Eternal Sunshine of the Spotless Mind',
        year: 2004,
    },
    { label: 'Amadeus', year: 1984 },
    { label: 'To Kill a Mockingbird', year: 1962 },
    { label: 'Toy Story 3', year: 2010 },
    { label: 'Logan', year: 2017 },
    { label: 'Full Metal Jacket', year: 1987 },
    { label: 'Dangal', year: 2016 },
    { label: 'The Sting', year: 1973 },
    { label: '2001: A Space Odyssey', year: 1968 },
    { label: "Singin' in the Rain", year: 1952 },
    { label: 'Toy Story', year: 1995 },
    { label: 'Bicycle Thieves', year: 1948 },
    { label: 'The Kid', year: 1921 },
    { label: 'Inglourious Basterds', year: 2009 },
    { label: 'Snatch', year: 2000 },
    { label: '3 Idiots', year: 2009 },
    { label: 'Monty Python and the Holy Grail', year: 1975 },
    { label: '2 The Shawshank Redemption', year: 1994 },
    { label: '2 The Godfather', year: 1972 },
    { label: '2 The Godfather: Part II', year: 1974 },
    { label: '2 The Dark Knight', year: 2008 },
    { label: '2 12 Angry Men', year: 1957 },
    { label: "2 Schindler's List", year: 1993 },
    { label: '2 Pulp Fiction', year: 1994 },
    {
        label: '2 The Lord of the Rings: The Return of the King',
        year: 2003,
    },
    { label: '2 The Good, the Bad and the Ugly', year: 1966 },
    { label: '2 Fight Club', year: 1999 },
    {
        label: '2 The Lord of the Rings: The Fellowship of the Ring',
        year: 2001,
    },
    {
        label: '2 Star Wars: Episode V - The Empire Strikes Back',
        year: 1980,
    },
    { label: '2 Forrest Gump', year: 1994 },
    { label: '2 Inception', year: 2010 },
    {
        label: '2 The Lord of the Rings: The Two Towers',
        year: 2002,
    },
    { label: "2 One Flew Over the Cuckoo's Nest", year: 1975 },
    { label: '2 Goodfellas', year: 1990 },
    { label: '2 The Matrix', year: 1999 },
    { label: '2 Seven Samurai', year: 1954 },
    {
        label: '2 Star Wars: Episode IV - A New Hope',
        year: 1977,
    },
    { label: '2 City of God', year: 2002 },
    { label: '2 Se7en', year: 1995 },
    { label: '2 The Silence of the Lambs', year: 1991 },
    { label: "2 It's a Wonderful Life", year: 1946 },
    { label: '2 Life Is Beautiful', year: 1997 },
    { label: '2 The Usual Suspects', year: 1995 },
    { label: '2 Léon: The Professional', year: 1994 },
    { label: '2 Spirited Away', year: 2001 },
    { label: '2 Saving Private Ryan', year: 1998 },
    { label: '2 Once Upon a Time in the West', year: 1968 },
    { label: '2 American History X', year: 1998 },
    { label: '2 Interstellar', year: 2014 },
    { label: '2 Casablanca', year: 1942 },
    { label: '2 City Lights', year: 1931 },
    { label: '2 Psycho', year: 1960 },
    { label: '2 The Green Mile', year: 1999 },
    { label: '2 The Intouchables', year: 2011 },
    { label: '2 Modern Times', year: 1936 },
    { label: '2 Raiders of the Lost Ark', year: 1981 },
    { label: '2 Rear Window', year: 1954 },
    { label: '2 The Pianist', year: 2002 },
    { label: '2 The Departed', year: 2006 },
    { label: '2 Terminator 2: Judgment Day', year: 1991 },
    { label: '2 Back to the Future', year: 1985 },
    { label: '2 Whiplash', year: 2014 },
    { label: '2 Gladiator', year: 2000 },
    { label: '2 Memento', year: 2000 },
    { label: '2 The Prestige', year: 2006 },
    { label: '2 The Lion King', year: 1994 },
    { label: '2 Apocalypse Now', year: 1979 },
    { label: '2 Alien', year: 1979 },
    { label: '2 Sunset Boulevard', year: 1950 },
    {
        label: '2 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
        year: 1964,
    },
    { label: '2 The Great Dictator', year: 1940 },
    { label: '2 Cinema Paradiso', year: 1988 },
    { label: '2 The Lives of Others', year: 2006 },
    { label: '2 Grave of the Fireflies', year: 1988 },
    { label: '2 Paths of Glory', year: 1957 },
    { label: '2 Django Unchained', year: 2012 },
    { label: '2 The Shining', year: 1980 },
    { label: '2 WALL·E', year: 2008 },
    { label: '2 American Beauty', year: 1999 },
    { label: '2 The Dark Knight Rises', year: 2012 },
    { label: '2 Princess Mononoke', year: 1997 },
    { label: '2 Aliens', year: 1986 },
    { label: '2 Oldboy', year: 2003 },
    { label: '2 Once Upon a Time in America', year: 1984 },
    { label: '2 Witness for the Prosecution', year: 1957 },
    { label: '2 Das Boot', year: 1981 },
    { label: '2 Citizen Kane', year: 1941 },
    { label: '2 North by Northwest', year: 1959 },
    { label: '2 Vertigo', year: 1958 },
    {
        label: '2 Star Wars: Episode VI - Return of the Jedi',
        year: 1983,
    },
    { label: '2 Reservoir Dogs', year: 1992 },
    { label: '2 Braveheart', year: 1995 },
    { label: '2 M', year: 1931 },
    { label: '2 Requiem for a Dream', year: 2000 },
    { label: '2 Amélie', year: 2001 },
    { label: '2 A Clockwork Orange', year: 1971 },
    { label: '2 Like Stars on Earth', year: 2007 },
    { label: '2 Taxi Driver', year: 1976 },
    { label: '2 Lawrence of Arabia', year: 1962 },
    { label: '2 Double Indemnity', year: 1944 },
    {
        label: '2 Eternal Sunshine of the Spotless Mind',
        year: 2004,
    },
    { label: '2 Amadeus', year: 1984 },
    { label: '2 To Kill a Mockingbird', year: 1962 },
    { label: '2 Toy Story 3', year: 2010 },
    { label: '2 Logan', year: 2017 },
    { label: '2 Full Metal Jacket', year: 1987 },
    { label: '2 Dangal', year: 2016 },
    { label: '2 The Sting', year: 1973 },
    { label: '2 2001: A Space Odyssey', year: 1968 },
    { label: "2 Singin' in the Rain", year: 1952 },
    { label: '2 Toy Story', year: 1995 },
    { label: '2 Bicycle Thieves', year: 1948 },
    { label: '2 The Kid', year: 1921 },
    { label: '2 Inglourious Basterds', year: 2009 },
    { label: '2 Snatch', year: 2000 },
    { label: '2 3 Idiots', year: 2009 },
    { label: '2 Monty Python and the Holy Grail', year: 1975 },
];
